### PR TITLE
Add IP option for X-REAL-IP

### PR DESCRIPTION
**Pull request by konsti**
Add option to get IP from `X-REAL-IP` header.

### CODE REVIEW

**Comment by gshaw** [comment]
What's the reason for the `X-REAL-IP` header.  Not against merging it, just curious as to the purpose.  Seems Nginx related but other than that Google isn't coming up with anything definitive.

**Comment by konsti** [comment]
As soon as your your app runs behind any kind of load balancer or proxy, every request to your app comes from that proxy.

Example:

```
name: web             -> haproxy/nginx -> rails app
ip:   123.123.123.123 -> 10.0.0.3      -> 10.0.0.3
```

A request goes from the ip `123.123.123.123` to your load balancer. The balancer sends the request to your rails app. The rails app now only sees the IP address of your balancer `10.0.0.3` and not the original IP address `123.123.123.123`.

It's normal to add 2 headers to any request in the load-balancer or proxy: `X-Forwarded-For` and `X-Real-IP` to make the original IP address available for the app.

It's best practice to use `X-Forwarded-For` to show the all proxies the request went through and `X-Real-IP` to carry the original client address along the way.

So if there is a `X-Real-IP` header available, the logger should use it in favour of the normal `IP`.

**Comment by konsti** [comment]
Any updates on this?

**Comment by gshaw** [comment]
Ack my bad.  New 1.0.0 gem pushed with this in it.

**Pull request merged**
